name: Chunklock
version: 1.2.7
main: me.chunklock.ChunklockPlugin
api-version: 1.20
author: LunaryCraft Dev Team
description: Advanced chunk-locking system with visual effects, glass borders and strategic progression
softdepend: [FancyHolograms]

commands:
  chunklock:
    description: Chunklock main command with full functionality including per-player worlds
    usage: /chunklock [status|start|reset <player>|bypass [player]|unlock|spawn|team <player>|reload|resetall|help]
    permission: chunklock.use
    aliases: [cl]

permissions:
  chunklock.use:
    description: Allows basic use of chunklock commands
    default: true
    children:
      chunklock.status: true
      chunklock.start: true
      chunklock.unlock: true
      chunklock.spawn: true
      chunklock.team: true

  chunklock.admin:
    description: Allows access to all admin functions including reload
    default: op
    children:
      chunklock.use: true
      chunklock.unlock: true
      chunklock.reset: true
      chunklock.bypass: true
      chunklock.reload: true
      chunklock.resetall: true

  chunklock.reload:
    description: Allows reloading the plugin configuration
    default: op

  chunklock.unlock:
    description: Allows force unlocking chunks for players (admin only)
    default: op

  chunklock.reset:
    description: Allows resetting player progress and chunks
    default: op

  chunklock.bypass:
    description: Allows toggling chunk bypass mode
    default: op
